# Generated by Django 4.2.11 on 2024-09-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abml', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
