# Generated by Django 4.2.16 on 2025-04-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningdata',
            name='iteration',
            field=models.IntegerField(default=0),
        ),
    ]
