# Generated by Django 4.2.11 on 2025-05-26 13:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abml', '0003_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningdata',
            name='inactive_attributes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
