# Generated by Django 4.2.11 on 2025-05-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abml', '0004_learningdata_inactive_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningdata',
            name='full_data',
            field=models.BinaryField(null=True),
        ),
    ]
