# Generated by Django 4.2.16 on 2025-06-06 13:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abml', '0005_learningdata_full_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='attributes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='domain',
            name='expert_attributes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
