# Generated by Django 4.2.16 on 2025-06-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abml', '0006_domain_attributes_domain_expert_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningdata',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
