# Generated by Django 4.2.16 on 2025-07-09 14:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abml', '0007_learningdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningdata',
            name='expert_attributes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
