# Generated by Django 4.2.16 on 2025-07-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abml', '0008_learningdata_expert_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='display_names',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='learningdata',
            name='display_names',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
