# Generated by Django 4.2.16 on 2025-07-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abml', '0009_domain_display_names_learningdata_display_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='attr_descriptions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='domain',
            name='attr_tooltips',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='learningdata',
            name='attr_descriptions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='learningdata',
            name='attr_tooltips',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
