# Generated by Django 4.2.16 on 2025-07-22 16:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abml', '0010_domain_attr_descriptions_domain_attr_tooltips_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration_number', models.IntegerField()),
                ('chosen_arguments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('learning_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iterations', to='abml.learningdata')),
            ],
        ),
    ]
