# Generated by Django 4.2.16 on 2025-07-23 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abml', '0011_learningiteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningdata',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='learningdata',
            unique_together={('user', 'name')},
        ),
    ]
