# Generated by Django 4.2.16 on 2025-07-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abml', '0012_alter_learningdata_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningiteration',
            name='mScore',
            field=models.FloatField(default=0.0),
        ),
    ]
