# Generated by Django 4.2.16 on 2025-07-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abml', '0014_alter_learningdata_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningiteration',
            name='selectedExampleId',
            field=models.CharField(default=''),
        ),
    ]
