# Generated by Django 4.2.16 on 2025-08-12 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abml', '0015_learningiteration_selectedexampleid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=100)),
                ('P_L', models.FloatField(default=0.2)),
                ('P_T', models.FloatField(default=0.15)),
                ('P_G', models.FloatField(default=0.25)),
                ('P_S', models.FloatField(default=0.1)),
                ('learning_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abml.learningdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'learning_data', 'attribute')},
            },
        ),
    ]
