# Generated by Django 4.2.28 on 2026-03-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abml', '0016_skillknowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningiteration',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='skillknowledge',
            name='P_G',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='skillknowledge',
            name='P_T',
            field=models.FloatField(default=0.1),
        ),
    ]
